spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school_vaccine
      database: school_vaccine

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8081
